config/routes.rb
Red::Application.routes.draw do
  get "amistad/crear"

  get "perfil/index"

  get "perfil/show"

  get "perfil/update"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :perfil, :only => [:index, :show, :update]

  match "nombre/:nombre" => "users#show"
  match "contacto/:id" =>"users#contacto"
  match "amistad/crear/:id" => "amistad#crear"
  match "amistades/aceptar/:nombre" =>"amistad#aceptar"
  match "amistades/rechazar/:nombre" =>"amistad#rechazar"

end

app/models/amigo.rb
class Amigo < ActiveRecord::Base
  belongs_to :user 
  belongs_to :amistad, :class_name=>"User", :foreign_key =>"amigo_id"
  attr_accessible :amigo_id, :estado, :user_id



  #Enviar petición de amistad

  def self.solicitar_amistad(usuario,amigo)
      self.create(:user_id=>usuario.id, :amigo_id=>amigo.id, :estado=>"pendiente")
      self.create(:user_id=>amigo.id, :amigo_id=>usuario.id, :estado=>"solicitado")
  end

  def self.existe_amistad?(usuario,amigo)
    find_by_user_id_and_amigo_id(usuario,amigo).nil? and usuario !=amigo
  end
  #Aceptar Amistad
  def self.aceptar_amistad(usuario,amigo)
    nuestra_fila = self.find_by_user_id_and_amigo_id(usuario.id,amigo.id)
    nuestra_fila.estado = "aceptado"
    nuestra_fila.save!
  end
 #Rechazar Amistad
  def self.rechazar_amistad(usuario,amigo)
    nuestra_fila = self.find_by_user_id_and_amigo_id(usuario.id,amigo.id)
    nuestra_fila.estado = "rechazado"
    nuestra_fila.save!
  end
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
	belongs_to :user
  # attr_accessible :title, :body
  attr_accessible :nombre, :apellidos, :sexo, :fecha_nacimiento, :ciudad, :imagen

    CAMPOS = %w(nombre apellidos sexo ciudad)
	SEXO = ["Hombre","Mujer"]

	

	#Tamaños
	validates :nombre,:apellidos,:ciudad, :length =>
	{
		:maximum=> 30
		
	},
	:format=> {:with=>/^[a-zA-Z]*( |\S)[a-zA-Z]*$/,
	:message=>"%{value}, formato no permitido"}


	validates :fecha_nacimiento,
	:format =>{:with => /^\d{4}\-\d{2}\-\d{2}$/,
	:message=>"%{value}, incorrecta"}




	validates :sexo, :inclusion=> {:in=>SEXO}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :perfil
	has_many :amigo
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/amistad_controller.rb
class AmistadController < ApplicationController
before_filter :authenticate_user!
  def crear
  	@usuario = current_user
  	@amigo = User.find(params[:id])

  	#Solicitar Amistad
  	 if Amigo.existe_amistad?(@usuario,@amigo)
  		Amigo.solicitar_amistad(@usuario,@amigo)

  		#Email amigo
  		Email.solicitar_amistad(@usuario,@amigo).deliver
  			#Mostrar mensaje - petición correcta
  		flash[:notice] = "Se ha realizado correctamente"
  		
  	else
  		flash[:notice] = "Ya existe amistad"
  	end
  	#Redireccionar
  		redirect_to @amigo
  end

  def aceptar
 	  @usuario = User.find_by_name(params[:nombre])
 
 	  Amigo.aceptar_amistad(@usuario,current_user)
 	  Amigo.aceptar_amistad(current_user,@usuario)

 	  redirect_to current_user
  end

  def rechazar 
    @usuario = User.find_by_name(params[:nombre])
    Amigo.rechazar_amistad(@usuario,current_user)
    Amigo.rechazar_amistad(current_user,@usuario)

    redirect_to current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.paginate(:page=>params[:page],:per_page=>6)

  end
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
before_filter :authenticate_user!
  def index
  end

  def show
  	@usuario = User.find(current_user)
  	@usuario.perfil ||= @usuario.build_perfil
  	@perfil = @usuario.perfil
  end

  def update

  	@usuario = User.find(current_user)
    @perfil = Perfil.new(params[:perfil])
    @usuario.perfil ||= @usuario.build_perfil

    respond_to do |format|
      if @perfil.save
          @usuario.perfil.update_attributes(params[:perfil])
          format.html {redirect_to @usuario, notice: "Datos Actualizados" }
      else
        format.html { render action: "show"}

      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   include ApplicationHelper

  before_filter :authenticate_user!, :except=>:show


  def index
    @users = User.all
  end

  def show
    if params[:id]
    	@user = User.find(params[:id])
	else
		@user = User.find_by_name(params[:nombre])
	end
end

def contacto
    @destinatario = User.find(params[:id])

    if request.post?
      if comprobar(params)
        flash[:notice] = "Se ha enviado correctamente"
      else
        flash[:alert] = "No se ha enviado correctamente"
      end
      redirect_to @destinatario
    end
  end
end

app/helpers/amistad_helper.rb
module AmistadHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def existe_amistad?(usuario,amigo)
		Amigo.existe_amistad?(usuario,amigo)
	end

	def tienes_amigos?(usuario)
    	!usuario.amigo.empty?
	end

	def nombre_perfil(usuario)
		if usuario.perfil 
			usuario.perfil.nombre.capitalize
		else
			usuario.name.capitalize
		end
	end

	def ciudad_perfil(usuario)
		if usuario.perfil 
			usuario.perfil.ciudad 
		else
			"Sin Especificar"
		end

	end

	def sexo_perfil(usuario)
		if usuario.perfil 
			usuario.perfil.sexo
		else
			"Sin Especificar"
		end

	end

	def existe_usuario(usuario)
		if usuario
			true
		end
	end

	def comprobar(params)
		!params[:asunto].blank? and !params[:mensaje].blank? and Email.enviar(params).deliver
	end
end

app/helpers/home_helper.rb
#encoding: utf-8
module HomeHelper
	def ciudad_usuario(usuario)
		if usuario.perfil
			usuario.perfil.ciudad 
		else
			"Sin especificar"
		end
	end
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/views/amistad/crear.html.erb
<h1>Amistad#crear</h1>
<p>Find me in app/views/amistad/crear.html.erb</p>

app/views/home/index.html.erb
<h3><em><p class="text-info">Usuarios Registrados</p></em></h3>

<% @users.each do |user| %>
<% if user != current_user %>
	<div class="content">
		<div class="row">
			<!-- Insertar avatar -->
			<div class="span1">
				<%=link_to gravatar_image_tag(user.email, :alt=>user.name),user_path(user)  %>
			</div>
			<!-- Fin avatar -->
			<!-- Nombre y descripción usuario -->
			<div class="span">
				<strong><%= user.name.capitalize %></strong>
				<p>
					<small>
						<%= ciudad_usuario(user) %>
					</small>
				</p>
			</div>
			<!-- Fin descripción-->
		</div>
	</div>
<% end %>
<% end %>


<%= will_paginate @users, :renderer => BootstrapPagination::Rails %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= label_tag "Red Social", nil , :class => 'brand' %>
<ul class="nav">
  <li class="divider-vertical"></li>
  <li>
  <%= link_to "Inicio", root_path %>
  </li>
  <li class="divider-vertical"></li>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Configuración de la Cuenta', users_path %>
    </li>
    <li class="divider-vertical"></li>
  <% else %>
    <li>
  <%= link_to 'Login', new_user_session_path %>
    </li>
    <li class="divider-vertical"></li>
  <% end %>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Salir', destroy_user_session_path, :method=>'delete' %>
    </li>
    <li class="divider-vertical"></li>
    <li>&nbsp;
    </li>
    <% else %>
    <li>
    <%= link_to 'Registro', new_user_registration_path %>
    </li>
    <li class="divider-vertical"></li>
  <% end %>
  </ul>
<% if user_signed_in? %>
<ul class="nav pull-right">
  <li class="dropdown">
    <div style="color: gray; height: 40px; font-size:14px; line-height: 40px;">Bienvenido &nbsp;<%= current_user.name.capitalize %></div>
    </ul>
  </li>
</ul>
<% end %>

   
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Red Social" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Red Social" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> 
    </div> 
  </body>
</html>

app/views/perfil/index.html.erb
<h1>Perfil#index</h1>
<p>Find me in app/views/perfil/index.html.erb</p>

app/views/perfil/show.html.erb
<h3><em><p class="text-info">Editar Perfil de <%= current_user.name.capitalize %></p></em></h3>

<%= form_for @perfil, :url=>{:action=>:update}, :html=>{:method=>:put} do |f| %>
 <% if @perfil.errors.any? %>
 <div class="alert alert-error">
      <a class="close" data-dismiss="alert">&#215;</a>
 
      <h2><%= pluralize(@perfil.errors.count, "error") %></h2>

      <ul>
      <% @perfil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p><%= f.label :nombre %>
<%= f.text_field :nombre %></p>

  <div><%= f.label :apellidos %>
  <%= f.text_field :apellidos %></div>

  <div><%= f.label :ciudad %>
  <%= f.text_field :ciudad %></div>

  <div><%= f.label :sexo %>
  <%= f.radio_button :sexo, "Hombre" %> Hombre
  <%= f.radio_button :sexo, "Mujer" %> Mujer
   </div><br/>

  <div><%= f.label :fecha_nacimiento, "Fecha de nacimiento" %>
  <%= f.date_select :fecha_nacimiento,
  :start_year => 1930,
  :end_year => Time.now.year,
  :include_blank =>true,
  :order => [:day, :month, :year] %></div><br/>



  <div><%= f.submit "Actualizar", :class=>"btn btn-success" %></div>
<% end %>


<%= link_to "Atrás", :back %>

app/views/perfil/update.html.erb
<h1>Perfil#update</h1>
<p>Find me in app/views/perfil/update.html.erb</p>

app/views/users/_contacto.html.erb
<h3><em><p class="text-info">Mensaje</p></em></h3>

<%= form_tag(:action=>"contacto", :id=>usuario) do %>
	<%= hidden_field_tag "destinatario", destinatario %>

	<%= label_tag "asunto", "Asunto" %>
	<%= text_field_tag "asunto" %>

	<%= label_tag "mensaje", "Mensaje" %>
	<%= text_area_tag "mensaje",nil, :size => "40x3" %>
	<p></p>
	<%= submit_tag "Enviar", :class=>"btn btn-success" %>
<% end %>

app/views/users/_listado_amigos.html.erb
<% if tienes_amigos?(usuario) %>
        <h3>Listado de Amigos</h3>
        <% usuario.amigo.each  do |usuario| %>
        
         <% if (usuario.estado == "aceptado") %>
           <p>
           <div class="row">
            <div class="span1"> 
                <%=link_to gravatar_image_tag(usuario.amistad.email, :alt=>usuario.amistad.name),user_path(usuario.amistad)  %>
            </div> 
            <div class="span2">
                <%= usuario.amistad.name.capitalize %> 
                <%= link_to "Ir perfil", user_path(usuario.amistad) %>
            </div>  
            
            </div>
        </p>
        <% end %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<h3>Configuración Cuenta</h3>

<div class="row">
	<div class="span3">
		<ul class="nav nav-list">
			<li class="nav-header">Menú Usuario</li>
    		<li>
    		<%= link_to 'Información Básica', edit_user_registration_path %>
    		</li>
    		<li>
    		<%= link_to 'Editar Perfil', perfil_path(current_user)%>
    		</li>
    	</ul>
	</div>
<!-- Mostrar Avatar del usuario -->
    <div class="span3">             
        <%= gravatar_image_tag(current_user.email, :alt => current_user.name,:class=>"thumbnail",:gravatar => { :size => 300 })  %> 
    </div>
    <div class="span3">
    <!-- Listar los usuario -->
        <%= render :partial=>"listado_amigos", :locals => {:usuario=> current_user} %>
    </div>
</div>
  

app/views/users/show.html.erb
<% if existe_usuario(@user) %>

<h3><em><p class="text-info">Perfil Público de <%= nombre_perfil(@user) %></p></em></h3>

		<div class="row">
  			<div class="span4">
  			<%= gravatar_image_tag(@user.email, :alt => @user.name,:class=>"thumbnail",:gravatar => { :size => 300 })  %>
  			</div>
  			<div class="span3 ">
  				<h3><em><p class="text-info"><%= nombre_perfil(@user) %></p></em></h3>
              <h5>Ciudad: <%= ciudad_perfil(@user) %></h5>
  						<h5>Sexo: <%= sexo_perfil(@user) %> </h5>
  					<%= render :partial=>"users/contacto", :locals =>{:destinatario=> @user.email,
            :usuario =>@user} %>
          </div>
        <div class="span3">
          <%= render :partial=>"listado_amigos", :locals => {:usuario=> @user} %>
        </div>

  		</div>
  		<div class="row">
  			<div class="span4">
         <!-- Comprobar si existe amistad, sino mostrar el enlace -->
         <% if existe_amistad?(current_user,@user) %>
         <%= link_to "Solicitud de amistad a #{@user.name.capitalize}",
         {:controller => "amistad",
          :action => "crear",
          :id => @user},
          :confirm => "Realmente quiere solicitar su amistad?" %>
  			<% end %>
        </div>
      </div>
<% else %>
	
	Lo sentimos nombre de usuario no válido 

<% end %>